### ISSUE TITLE
Update Zepto

### ISSUE THREAD

**Issue by moimael** [e-sites/Zepto-Builder#9]
Right now we can only build zepto 1.1.4, since 1.1.6 is out, could you upgrade ?

Thanks !

**Comment by boye** [comment]
Zepto Builder fetches the latest version from Zepto's master branch on GitHub, so the modules are up to date. Though, since their [package.json](https://github.com/madrobby/zepto/blob/master/package.json#L3) still needs a version bump it displays version 1.1.4.

**Comment by boye** [comment]
@moimael It's fixed now ;)

**Comment by moimael** [comment]
@boye  Thanks a lot ! :)
